version: 2
jobs:
  lint:
    docker:
      - image: cimg/node:14.8.0

    steps:
      - checkout

      - restore_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependecies
          command: npm ci --cache .npm-cache

      - save_cache:
          paths:
            - .npm-cache
          key: npm-packages-{{ checksum "package-lock.json" }}

      - run:
          name: Lint code
          command: npm run test:eslint

      - run:
          name: Check typescript
          command: npm run test:typescript

  build:
    docker:
      - image: cimg/node:14.8.0

    steps:
      - checkout

      - restore_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependecies
          command: npm ci --cache .npm-cache

      - save_cache:
          paths:
            - .npm-cache
          key: npm-packages-{{ checksum "package-lock.json" }}

      - run:
          name: Buid Application
          command: npm run build:prod

      - persist_to_workspace:
          root: .
          paths:
            - dist/

  deploy:
    machine:
      enabled: true

    steps:
      - add_ssh_keys:
          fingerprints:
            - "f2:08:46:6e:62:14:29:6d:7c:8b:e5:f1:e2:52:00:fb"

      - attach_workspace:
          at: .

      - run:
          name: Deploy Over SSH
          command: scp -r ./dist/* $SSH_USER@$SSH_HOST:$SSH_SERVE_PATH

workflows:
  version: 2
  lint_build_deploy:
    jobs:
      - lint

      - build:
          requires:
            - lint

#      - deploy:
#          requires:
#            - lint
#            - build
#
#          filters:
#            branches:
#              only: master
