version: 2
jobs:
  lint:
    docker:
      - image: cimg/node:14.8.0

    steps:
      - checkout

      - restore_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependecies
          command: npm ci --cache .npm-cache

      - save_cache:
          paths:
            - .npm-cache
          key: npm-packages-{{ checksum "package-lock.json" }}

      - run:
          name: Lint code
          command: npm run test:eslint

  build:
    docker:
      - image: cimg/node:14.8.0

    steps:
      - checkout

      - restore_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependecies
          command: npm ci --cache .npm-cache

      - save_cache:
          paths:
            - .npm-cache
          key: npm-packages-{{ checksum "package-lock.json" }}

      - run:
          name: Buid Application
          command: npm run build:prod

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build:
          requires:
            - lint
